steps:
  - label: ":golang: Build"
    plugins:
      - docker#v5.11.0:
          image: "golang:1.18.0"
    command: "go build -o hello/hello ./hello"
    artifact_paths:
      - "hello/hello"

  - block: ":raised_hand: Approve"
    prompt: "Ready to continue?"

  - block: ":hand: Enter your name"
    prompt: "Please enter your name"
    fields:
      - text: "Name"
        key: "user-name"
        required: true

  - label: ":wave: Say Hello"
    command: |
      buildkite-agent artifact download "hello/hello" .
      chmod +x hello/hello
      NAME=$$(buildkite-agent meta-data get "user-name")
      ./hello/hello "$$NAME"