steps:
  # Lint - runs on all branches
  - label: ":mag: Lint"
    plugins:
      - golangci-lint#v1.0.0:
          use_docker: true

  # Test - runs on all branches
  - label: ":test_tube: Test"
    plugins:
      - docker#v5.11.0:
          image: "golang:1.18.0"
    command: "go test -v ./..."

  # Build - only on main
  - label: ":golang: Build"
    branches: "main"
    plugins:
      - docker#v5.11.0:
          image: "golang:1.18.0"
    command: "go build -o hello/hello ./hello"
    artifact_paths:
      - "hello/hello"

  - block: ":raised_hand: Approve"
    branches: "main"
    prompt: "Ready to continue?"

  - block: ":hand: Enter your name"
    branches: "main"
    prompt: "Please enter your name"
    fields:
      - text: "Name"
        key: "user-name"
        required: true

  - label: ":wave: Say Hello"
    branches: "main"
    command: |
      buildkite-agent artifact download "hello/hello" .
      chmod +x hello/hello
      NAME=$$(buildkite-agent meta-data get "user-name")
      ./hello/hello "$$NAME"

notify:
  - email: "simone.bennett@outlook.com"
    if: build.branch == "main"